---
- hosts:  all
  become:  true
  become_user:  root

  tasks:
  - name:  My program installs 
    apt:
      name:  tree


  - name: Copy aliases file to client
    copy:
      src: .bash_aliases
      dest: .bash_aliases
